# Generated by Django 3.0.8 on 2020-11-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201126_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='mcategory',
        ),
    ]
