# Generated by Django 3.0.8 on 2020-10-23 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_ourprojects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourprojects',
            options={},
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='status',
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourprojects',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
