# Generated by Django 3.0.8 on 2020-10-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201023_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourprojects',
            name='author',
        ),
    ]
