# Generated by Django 3.0.8 on 2020-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_ourprojects_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
