# Generated by Django 3.0.8 on 2020-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201023_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='arenda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='arenda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pricerenda',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
