# Generated by Django 3.0.8 on 2020-11-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201118_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricerenda',
        ),
    ]
